# Generated by Django 3.1.2 on 2020-11-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201124_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='staff',
        ),
    ]
